### ISSUE TITLE
Searchコマンドを削るか否か

### ISSUE THREAD

**Issue by ghost** [denx-official/huskey#1]
入力されたキーワードからデータセットを検索するコマンドとして `search` を用意していたが、これだけだと何を検索しているのかがイマイチわからない気がする。  
なので例えば、

```
huskey list hoge --search="discord"
```

とか、

```
huskey list hoge --grep="^.*google.*$"
```

みたいに、オプションから検索できたほうが覚えるコマンド数が減り、より直感的に操作できるように感じるのだがどうだろう？

**Comment by ippee** [comment]
listコマンドで取得した後、grepで指定すればよいので削除。
